apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrwer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrwer
  template:
    metadata:
      labels:
        app: wrwer
    spec:
      containers:
      - image: okteto.dev/wrwer:latest
        name: wrwer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2f136a38-dd75-4a5c-83c7-ddbd1b5bca05"
        - name: Vless_Path
          value: "/jkduerrijrgr897"
        - name: Vmess_UUID
          value: "2f136a38-dd75-4a5c-83c7-ddbd1b5bca05"
        - name: Vmess_Path
          value: "/uiytrwe5tfe5"
        - name: Share_Path
          value: "/v2link"
